### ISSUE TITLE
www.aut.bme.hu csak HTTPS-el működik, így labor gépeken nem lehet encryptálni

### ISSUE THREAD

**Issue by tibitoth** [VIAUAC00/Web-labor#3]
Lehetne a leírásban origo.hu, vagy legközelebb a labor image telepítése során legyen feltelepítve a tanúsítvány

**Comment by nkelemen18** [comment]
Én azt mondtam a hallgatóknak, hogy írják elé, hogy http:// és akkor legalább az első kérés - ami egy 302-es redirect - megnézhető formában van. Érdekes, de néhány gépen a fiddler látja a https tartalmát is (IL206).

**Comment by tibitoth** [comment]
egyértelműsítva van már a leírásban
